name:                cobot-io
version:             0.1.2.3
github:              "less-wrong/cobot-io"
license:             BSD3
category:            Bio 
author:              "Pavel Yakovlev, Bogdan Neterebskii, Alexander Sadovnikov"
maintainer:          "pavel@yakovlev.me"
copyright:           "2018-2019, Less Wrong Bio"
synopsis:            Biological data file formats and IO

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/less-wrong/cobot-io#readme>

dependencies:
- base >= 4.7 && < 5
- data-msgpack >= 0.0.9 && < 0.1
- text >= 1.2.2.1 && < 1.3
- bytestring >= 0.10.8.1 && < 0.11
- split
- attoparsec >= 0.10 && < 0.14
- binary >= 0.8.3.0 && < 1.0
- mtl >= 2.2.1 && < 2.3.0
- hyraxAbif >= 0.2.3.15 && < 0.2.4.0
- containers >= 0.5.7.1 && < 0.7
- http-conduit >= 2.3 && < 2.4
- array >= 0.5 && < 0.6
- deepseq >= 1.4 && < 1.5
- lens >= 4.16 && < 5.0
- linear >= 1.20 && < 1.21
- vector

library:
  source-dirs: src
  default-extensions:
    - DeriveGeneric
    - DeriveFunctor
    - DeriveFoldable
    - DeriveAnyClass
    - FlexibleInstances
    - InstanceSigs
    - MultiParamTypeClasses
    - RecordWildCards
    - ScopedTypeVariables
    - OverloadedStrings
    - TypeApplications
    - TypeFamilies
    - DataKinds
    - ConstraintKinds
    - TypeOperators
    - TemplateHaskell
    - FlexibleContexts
      

tests:
  cobot-io-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
      - OverloadedStrings
      - TypeFamilies
    dependencies:
    - cobot-io
    - directory
    - QuickCheck >= 2.9.2 && < 2.14
    - hspec >= 2.4.1 && < 2.8
    - neat-interpolation >= 0.3
    - linear >= 1.20 && < 1.21
