name:                cobot-io
version:             0.1.4.2
github:              "biocad/cobot-io"
license:             BSD3
category:            Bio
author:              "Pavel Yakovlev, Bogdan Neterebskii, Alexander Sadovnikov"
maintainer:          "pavel@yakovlev.me"
copyright:           "2020, Biocad"
synopsis:            Biological data file formats and IO

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/biocad/cobot-io#readme>

dependencies:
- base >= 4.14 && < 5
- array >= 0.5 && < 0.6
- attoparsec >= 0.10 && < 0.15
- binary >= 0.8.3.0 && < 1.0
- bytestring >= 0.10.8.1 && < 0.11
- cobot >= 0.1.1.7 
- containers >= 0.5.7.1 && < 0.7
- data-msgpack >= 0.0.9 && < 0.1
- deepseq >= 1.4 && < 1.5
- http-conduit >= 2.3 && < 2.4
- hyraxAbif >= 0.2.3.27 && < 0.2.4.0
- lens >= 4.16 && < 5.1
- linear >= 1.20 && < 1.22
- megaparsec >= 9.0.1
- mtl >= 2.2.1 && < 2.3.0
- parser-combinators >= 1.2.1
- split
- text >= 1.2.2.1 && < 1.3
- vector

library:
  source-dirs: src
  default-extensions:
    - DeriveGeneric
    - DeriveFunctor
    - DeriveFoldable
    - DeriveAnyClass
    - FlexibleInstances
    - InstanceSigs
    - MultiParamTypeClasses
    - RecordWildCards
    - ScopedTypeVariables
    - OverloadedStrings
    - TypeApplications
    - TypeFamilies
    - DataKinds
    - ConstraintKinds
    - TypeOperators
    - TemplateHaskell
    - FlexibleContexts


tests:
  cobot-io-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
      - OverloadedStrings
      - TypeFamilies
    dependencies:
    - cobot-io
    - directory
    - QuickCheck >= 2.9.2 && < 2.15
    - hspec >= 2.4.1 && < 2.9
    - neat-interpolation >= 0.3
    - linear
