module Bio.GB.Functions where

import Debug.Trace
import Data.Attoparsec.Text
import Bio.GB.Parser
import Bio.GB.Writer
import Bio.Sequence
import Bio.GB.Type
import Data.Text.IO as TIO
import Data.Text as T
import Data.Vector as V
import Data.List as L
import Control.Lens
import Data.Map.Strict as M
import Data.Maybe
import Control.Monad

type Name = Text


changeInsertion :: IO ()
changeInsertion = do
    gb <- readAndParse "/tmp/plasmid_maps/pSXn-IgG4HCpos-NR_BCD216-00_ABVH_000_01.gb"
    Control.Monad.forM_ changes $ \(newName, newSeq) -> do
        let res = updateGB "BCD216-00_ABVH_000_01" newName newSeq gb
        let newFile = genName newName
        let newGB   = genBankToText res
        TIO.writeFile newFile newGB
  where
    genName :: Text -> FilePath
    genName t = "/tmp/plasmid_maps/pSXn-IgG4HCpos-NR_" <> T.unpack t <> ".gb"



readAndParse :: FilePath -> IO GenBankSequence
readAndParse path = do
    content <- TIO.readFile path
    case parseOnly genBankP content of
        Left e -> error e
        Right r -> pure r

updateGB :: Name -> Name -> Text -> GenBankSequence -> GenBankSequence
updateGB oldFeatureName newFeatureName newSeq GenBankSequence{..} = GenBankSequence meta newGbSeq
  where
    newSeqVector = V.fromList . T.unpack $ newSeq

    newGbSeq = trace (show newFullSeq) $ trace (show updatedFeature) unsafeMarkedSequence (V.toList newFullSeq) (updatedFeature:movedFeatures) 
    
    oldMarkings = gbSeq ^. markings
    (featuresToUpdate, featuresToMove) = L.partition (needFeatureUpdate oldFeatureName) oldMarkings

    (oldFeature, location) = case featuresToUpdate of
                                 [(f, l)] -> (f, l)
                                 _ -> error "Too many features to update"
    
    (newFullSeq, offset, delta) = updateSequence (gbSeq ^. sequ) location newSeqVector
    
    updatedFeature = updateFeature (oldFeature, location)
                                   oldFeatureName
                                   newFeatureName
                                   newSeqVector
    movedFeatures = moveMarking (offset, delta) <$> featuresToMove 

-- | If feature has the same name as feature that we need to update
--
needFeatureUpdate :: Name -> (Feature, Range) -> Bool
needFeatureUpdate nameToUpdate (Feature {..}, _) 
    = isJust . L.find ((== nameToUpdate) . snd) $ fProps

updateFeature :: (Feature, Range) -- feature with range
              -> Name             -- name of the feature to update
              -> Name             -- name of the new feature
              -> Vector Char      -- sequence of the new feature
              -> (Feature, Range) 
updateFeature (Feature {..}, (start, _)) oldName newName newSeq 
    = (Feature fName fStrand53 newProps, (start, start + V.length newSeq))
  where
    newProps = [ if v == oldName then (k, newName) else (k, v)
               | (k, v) <- fProps
               ]

type Offset = Int
type Delta  = Int

updateSequence :: Vector a -> (Int, Int) -> Vector a -> (Vector a, Offset, Delta)
updateSequence initial (start, end) partToChange = (updatedVector, start, delta)
  where
    before = V.take start initial
    after  = V.drop end   initial 
    updatedVector = before <> partToChange <> after

    delta = V.length partToChange - (end - start)
    
moveMarking :: (Offset, Delta) -> (marking, Range) -> (marking, Range)
moveMarking (offset, delta) (mk, (start, end))
    | start < offset && end <= offset = (mk, (start, end))
    | offset <= start && offset < end = (mk, (start + delta, end + delta))
    | otherwise = error "updateMarking: offset is in the marking"

changes :: [(Name, Text)]
changes = 
  [ ("BCD216-01_OptMVH_001_01", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCTACTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGACACAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATTTTTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_02", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTACACATTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAACAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATAGGGATTACTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_03", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCACATACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAGCAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATCACTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_04", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTTACTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCCAGCCTAGCGGACAGAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATTTTTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_05", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATACAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGACAGCACACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATCAGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_06", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATACAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGACAGTTCACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATAGGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_07", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTGCCTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAGCAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATCACGATTACTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_08", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTGCCTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAGCAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATCAGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_09", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTCACTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAACCCTAGCGGACAGAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATAGGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_10", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTGCCTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCACACCTAGCGGACAGAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATAGGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_11", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTAACTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCACACCTAGCGGACAGAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATCAGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_12", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTAACTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCGCCCCTAGCGGACAGAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATCAGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_13", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTAACTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGATACAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATCACTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_14", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCAGTTACAGGGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAGCAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTACGATTACTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_15", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCGAGTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAACAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATAGGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_16", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCGAGTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAGCCAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATTTTTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_17", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTCGCTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAACAAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATTTTTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_18", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTCAGTTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAACAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATTTTTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_19", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCAGTTACTTCGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAACGGACAGAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATAGGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_20", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCAGTTACTTCGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTTACGGACAGAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATAGGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_21", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCGCCTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAGCAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTACGATTACTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_22", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCTTTACATTCAACTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAGCGGAAGCAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATACAGATTACTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  , ("BCD216-01_OptMVH_001_23", "CAAGTTCAGTTAGTCGAAAGCGGAGGCGGCTTAGTCCAACCTGGAGGATCTCTGCGTCTGTCCTGCGCAGCAAGTGGCCACACATTCAGTTACTATGATATTCAGTGGGTTCGTCAAGCCCCTGGCAAGGGTCTGGAGTGGGTCAGTAGTATCAGCCCTAACGGACAGAGTACGTATTACAGACGTGAGGTCAAGGGCCGTTTCACGATCAGCCGCGATAATAGCAAGAATACGTTGTACTTGCAAATGAACAGTCTGCGCGCTGAGGATACAGCAGTTTATTATTGTGCCCGTAGAACAGGAAGAGAGTACGGCGGAGGCTGGTATTTCGATCAGTGGGGACAGGGCACATTAGTCACCGTTAGCTCA")
  ]
