name: test

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Unit tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: ["8.10.4"]
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'
      - run: stack test --system-ghc --pedantic


